name: chatter_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/chat_icon.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true

# #for using cupertino icons
  cupertino_icons: ^1.0.2

  #for integrating firebase
  firebase_core: ^2.10.0
  
  #for handling firebase authentication
  firebase_auth: ^4.4.2
  
  #for handling google sign
  google_sign_in: ^6.1.0
  
  #for accessing cloud firestore database
  cloud_firestore: ^4.5.3
  
  #for showing network images
  cached_network_image: ^3.2.3
  
  #for picking images
  image_picker: ^0.8.7+4
  
  #for accessing firebase storage (for uploading file)
  firebase_storage: ^11.1.1
  
  #for showing emojis
  emoji_picker_flutter: ^1.5.4

  # For accessing firebase messaging (Push Notification)
  firebase_messaging: ^14.4.1

  #for calling RestAPIs
  http: ^0.13.6

  #for creating notification channel
  flutter_notification_channel: ^2.0.0

  #for storing images into gallery
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
